title: Data Engineering Blog
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://anittasaju1996.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Anitta Therattil # add your name
author-img: david-freeman.jpg # add your photo
about-author: A curious Data Engineer making her way through the Big Data Tech Stack # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: anittasaju1996 # add your Github handle
social-linkedin: anitta-therattil # add your Linkedin handle
social-email: anittasaju1996@naver.com # add your Email address

# Disqus
discus-identifier:  # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - webrick

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
